import { useEffect, useState } from 'react';
import { ShieldCheck, UserCog } from 'lucide-react';
import { usePlatformConsole } from '../hooks/usePlatformConsole';
import { Header, Notice } from './PlatformHome';

export default function PlatformAdmins() {
  const { admins, adminCandidates, error, loading, loadAdmins, setPlatformAdmin } = usePlatformConsole();
  useEffect(() => { loadAdmins().catch(() => {}); }, [loadAdmins]);
  const [candidateId, setCandidateId] = useState('');
  async function toggle(admin) { try { await setPlatformAdmin(admin.id, false); } catch (_) {} }
  async function promote() { if (!candidateId) return; try { await setPlatformAdmin(candidateId, true); setCandidateId(''); } catch (_) {} }
  return <div className="space-y-7"><Header eyebrow="ACCESS CONTROL" title="Administradores" subtitle="Acceso de plataforma separado de los roles de tenant." />{error && <Notice>{error}</Notice>}<div className="rounded-xl p-5" style={{ background: 'var(--gc-surface)', border: '1px solid var(--gc-border)' }}><div className="mb-3 text-sm font-medium text-white">Agregar Platform Admin</div><div className="flex gap-2"><select value={candidateId} onChange={(event) => setCandidateId(event.target.value)} className="min-w-0 flex-1 rounded-lg px-3 py-2 text-xs text-white" style={{ background: 'var(--gc-input)', border: '1px solid var(--gc-border)' }}><option value="">Seleccionar usuario Auth existente</option>{adminCandidates.map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.name} · {candidate.email}</option>)}</select><button onClick={promote} disabled={!candidateId} className="rounded-lg px-3 py-2 text-xs text-white disabled:opacity-50" style={{ background: '#6D5CE7' }}>Promover</button></div></div><div className="rounded-xl" style={{ background: 'var(--gc-surface)', border: '1px solid var(--gc-border)' }}><div className="flex items-center gap-2 border-b px-5 py-4 text-sm font-medium text-white" style={{ borderColor: 'var(--gc-border)' }}><UserCog size={16} className="text-[#8B7CFF]" /> Platform Admins</div>{loading && !admins.length ? <div className="p-8 text-xs text-gray-500">Cargando…</div> : admins.length ? <div className="divide-y" style={{ borderColor: 'var(--gc-border)' }}>{admins.map((admin) => <div key={admin.id} className="flex items-center justify-between gap-4 px-5 py-4"><div><div className="text-sm text-white">{admin.name}</div><div className="text-xs text-gray-500">{admin.email}</div><div className="mt-1 text-[10px] text-gray-600">Último acceso: {admin.last_sign_in_at ? new Date(admin.last_sign_in_at).toLocaleString('es-MX') : 'Sin acceso'}</div></div><button onClick={() => toggle(admin)} className="inline-flex items-center gap-1.5 rounded-lg px-3 py-2 text-xs text-amber-300" style={{ border: '1px solid rgba(245,158,11,.25)' }}><ShieldCheck size={13} /> Retirar</button></div>)}</div> : <div className="p-8 text-center text-xs text-gray-500">No hay administradores de plataforma disponibles.</div>}</div><p className="text-xs text-gray-600">Solo se pueden promover usuarios Auth existentes; no se crean usuarios desde esta vista.</p></div>;
}
